config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "rooms#search"
  get 'bookings/index'
  devise_for :customers
  root "bookings#index"

  
  # resources :charges, only: [:new, :create]

  get 'bookings/bookings'

   resources :roomtypes
  
   resources :rooms do  resources :bookings
    end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)



  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :booking_date, presence: true

end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_one_attached :id_proof
has_one_attached :address_proof
has_one_attached :profile_image
# has_many :bookings
# has_many :rooms
has_many :bookings
has_many :rooms, through: :bookings


def create_on_stripe
  params = { email: email, name: name }
  response = Stripe::Customer.create(params)
  self.stripe_id = response.id
end
end

app/models/order.rb
  class Order < ApplicationRecord
    attr_accessor :credit_card_number, :credit_card_exp_month, :credit_card_exp_year, :credit_card_cvv
    belongs_to :customer
    has_one :payment
    after_create :create_payment
    # Add as much as you need
    # Example: enum payment_method: %i[credit_card ach boleto]
    enum payment_method: %i[credit_card]
    def create_payment
      params = {
        order_id: id,
        credit_card_number: credit_card_number,
        credit_card_exp_month: credit_card_exp_month,
        credit_card_exp_year: credit_card_exp_year,
        credit_card_cvv: credit_card_cvv
      }
      Payment.create!(params)
    end
  end

app/models/paying.rb
class Paying < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord

  validates :roomnumber, uniqueness:true 
  belongs_to :roomtype 

  enum :status, [:available , :unavailable]
  # has_one :booking



  # belongs_to :customer

has_many :bookings ,dependent: :destroy
has_many :customers, through: :bookings

end

app/models/roomtype.rb
class Roomtype < ApplicationRecord

  has_one_attached :roomimg
  enum :status,[:booked , :opentobook]

  has_many :rooms , dependent: :destroy

  validates :roomtype, presence: true
  validates :cost, presence: true
  validates :description, presence: true



end 

app/controllers/git.rb
git add .
git commit -m "mailer"
git push origin hms

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class Api::V1::OrdersController < ApplicationController
  def create
    @order = Order.new(order_params.merge(amount_cents: rand(1000..10000), payment_method: 'credit_card'))
    if @order.save
      render json: { order: @order, payment: @order.payment }, status: :created
    else
      render json: @response.errors, status: :unprocessable_entity
    end
  end
  private
  def order_params
    params.require(:data).permit(:customer_id, :credit_card_number, :credit_card_exp_month, :credit_card_exp_year, :credit_card_cvv)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def index
      @rooms = Room.all
    end
  
    def new
      @room = Room.new
    end
  
    def create
      @room = Room.new(room_params)
      if @room.save
        flash[:success] = 'Rooms has been added Successfully!'   
  
        redirect_to  rooms_path	
      else
        render :new, status: :unprocessable_entity
      end
    end
  
     def show
        @room = Room.find(params[:id])
        flash[:notice] = 'This is Your Room List'
      end
  
      def edit
        @room = Room.find(params[:id])
       end
    
    def search
       @roomtype  = params[:roomtype]
       @results = Roomtype.where("roomtype LIKE ?", "%#{@roomtype}%")
      end

    def update
      @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = 'Product has been Updated Successfully!'   
      redirect_to rooms_path
    else
          render :edit, status: :unprocessable_entity
      end
    end
      
  private

  def room_params
    params.require(:room).permit(:roomtype_id, :roomnumber, :description, :status)
  end
  
  end

app/controllers/roomtypes_controller.rb
class RoomtypesController < ApplicationController

  def index
    @roomtypes = Roomtype.all
  end

  def new
    @roomtype = Roomtype.new
  end

  def create
    @roomtype = Roomtype.new(roomtype_params)
    if @roomtype.save
      flash[:success] = 'Roomtype has been added Successfully!'   

      redirect_to  roomtypes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

   def show
      @roomtype = Roomtype.find(params[:id])
      flash[:notice] = 'This is Your Roomtype List'
    end

    def edit
      @roomtype = Roomtype.find(params[:id])
     end
  

     def update
      @roomtype = Roomtype.find(params[:id])
      if @roomtype.update(roomtype_params)
        flash[:notice] = 'Romtype has been Updated Successfully!'   


        redirect_to roomtypes_path

      else
        render :edit, status: :unprocessable_entity
      end
    end
    
private
def roomtype_params
  params.require(:roomtype).permit(:roomtype, :roomimg, :description, :cost, :status)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
 
end
def flash_class(level)
  bootstrap_alert_class = {
    "success" => "alert-success",
    "error" => "alert-danger",
    "notice" => "alert-info",
    "alert" => "alert-danger",
    "warn" => "alert-warning"
  }
  bootstrap_alert_class[level]

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/roomtypes_helper.rb
module RoomtypesHelper
end

app/views/roomtypes/_form.html.erb
<center>

<%= form_with model: @roomtype do |form| %>
<div class = 'card'>
    <div >
    <%= form.label :roomtype %><br>
    <%= form.text_field :roomtype %>
     <% @roomtype.errors.full_messages_for(:roomtype).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
</div>

  <div>
    <%= form.label :cost %><br>
    <%= form.text_area :cost %>
    <% @roomtype.errors.full_messages_for(:cost).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @roomtype.errors.full_messages_for(:description).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
  </div>
  </div>


  <div>
     <%= form.label :roomimg %>
    <%= form.file_field:roomimg %><br>
  </div>
<%= form.select :status, options_for_select(Roomtype.statuses.map {|k, v| [k.humanize.capitalize, k]}) %>


  <div>
    <%= form.submit %>
  </div>
  </div>
  </center>

<% end %>

app/views/roomtypes/create.html.erb
<h1>Roomtypes#create</h1>
<p>Find me in app/views/roomtypes/create.html.erb</p>

app/views/roomtypes/destroy.html.erb
<h1>Roomtypes#destroy</h1>
<p>Find me in app/views/roomtypes/destroy.html.erb</p>

app/views/roomtypes/edit.html.erb
<h1>Edit Stocks</h1>

<%= render "form", roomtype: @roomtype %>

app/views/roomtypes/index.html.erb
<h1>Room Types</h1>

<div class="btn btn-primary">
  <%= link_to 'Add Room Types', new_roomtype_path, :class => "btn btn-sm", style:"border-color:#70ff7b",style:" background-color:#abff8f"%> 
</div>


  <br>



<table id="book" border="3" layout= "fixed" width=" 100%"  >
<br>
  
  <tr>
    <th>roomtype</th>
    <th>description</th>
    <th>cost</th>
    <th> status</th>
    <th> image</th>

    <th> Action</th>
   
  </tr>

<% @roomtypes.each do |stock| %>  
  <tr >
    <td><%= stock.roomtype%></td>
    <td><%= stock.description %></td>
    <td><%= stock.cost %></td>
    <td><%= stock.status %></td>
    <td>
     <%=image_tag stock.roomimg , style: "width:200px; display: block"%>

</td>


   <td> <%= link_to 'Edit', edit_roomtype_path(stock) ,style:"color:#ac0dfd"%>   

     <%= link_to 'Show', roomtype_path(stock) %>   
</td>

  </tr>
<% end %>
</table>

app/views/roomtypes/new.html.erb
<h1>New Product</h1>

<%= render "form", roomtype: @roomtype %>

app/views/roomtypes/show.html.erb
<div class="container">  
<div class = "card">      
       
            <div>   
              <label>Stock Name</label>   
              <%= @roomtype.roomtype %>   
            </div>   
  
            <div>   
              <label>Price</label>   
              <%= @roomtype.description %>   
            </div>   
            
            <div>   
              <label>Description</label>   
              <%= @roomtype.cost %>   
            </div>   
         
             
            <div>   
              <label>Country</label>   
              <%= @roomtype.status %>   
            </div>   
         
     <%=image_tag(@roomtype.roomimg)%>
        
      </div>
</div>  

app/views/roomtypes/update.html.erb
<h1>Roomtypes#update</h1>
<p>Find me in app/views/roomtypes/update.html.erb</p>