config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "rooms#search"
  get 'bookings/index'
  devise_for :customers
  root "bookings#index"

  
  # resources :charges, only: [:new, :create]

  get 'bookings/bookings'

   resources :roomtypes
  
   resources :rooms do  resources :bookings
    end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)



  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :booking_date, presence: true

end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_one_attached :id_proof
has_one_attached :address_proof
has_one_attached :profile_image
# has_many :bookings
# has_many :rooms
has_many :bookings
has_many :rooms, through: :bookings


def create_on_stripe
  params = { email: email, name: name }
  response = Stripe::Customer.create(params)
  self.stripe_id = response.id
end
end

app/models/order.rb
  class Order < ApplicationRecord
    attr_accessor :credit_card_number, :credit_card_exp_month, :credit_card_exp_year, :credit_card_cvv
    belongs_to :customer
    has_one :payment
    after_create :create_payment
    # Add as much as you need
    # Example: enum payment_method: %i[credit_card ach boleto]
    enum payment_method: %i[credit_card]
    def create_payment
      params = {
        order_id: id,
        credit_card_number: credit_card_number,
        credit_card_exp_month: credit_card_exp_month,
        credit_card_exp_year: credit_card_exp_year,
        credit_card_cvv: credit_card_cvv
      }
      Payment.create!(params)
    end
  end

app/models/paying.rb
class Paying < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord

  validates :roomnumber, uniqueness:true 
  belongs_to :roomtype 

  enum :status, [:available , :unavailable]
  # has_one :booking



  # belongs_to :customer

has_many :bookings ,dependent: :destroy
has_many :customers, through: :bookings

end

app/models/roomtype.rb
class Roomtype < ApplicationRecord

  has_one_attached :roomimg
  enum :status,[:booked , :opentobook]

  has_many :rooms , dependent: :destroy

  validates :roomtype, presence: true
  validates :cost, presence: true
  validates :description, presence: true



end 

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
   @rooms = Room.all
end

def bookings
    @bookings = current_customer.bookings
    @roomtype = Roomtype.all
  end


  def new
    @booking = Booking.new
    @room = Room.all
    @room = Room.find(params[:room_id])
  end

  def create
    @room = Room.find(params[:room_id])
    @booking = @room.bookings.create(booking_params)
    @room.update(status:"unavailable")

  if @booking.check_out
    @days = (@booking.check_out.to_date - @booking.check_in.to_date).to_i
    @booking.charges = @booking.room.roomtype.cost * @days
  end 
   
    if @booking.save
        BookingMailer.with(customer: current_customer, booking: @booking).welcome_email .deliver_now
      flash[:success] = 'Booking has been Done Successfully!'   
      redirect_to  root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
     @booking = Booking.find(params[:id])
     @booking.destroy

    flash[:success] = 'Booking has been Delete Successfully!'   
    redirect_to bookings_bookings_path, status: :see_other
  end

 private
  def booking_params
    params.require(:booking).permit(:customer_id, :booking_date, :check_in, :check_out)
  end
end 

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  rescue_from Stripe::CardError, with: :catch_exception
  def new
  end

  def create
    StripeChargesServices.new(charges_params, current_user).call
    redirect_to new_charge_path
  end

  private

  def charges_params
    params.permit(:stripeEmail, :stripeToken, :order_id)
  end

  def catch_exception(exception)
    flash[:error] = exception.message
  end
end

app/controllers/git.rb
git add .
git commit -m "mailer"
git push origin hms

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class Api::V1::OrdersController < ApplicationController
  def create
    @order = Order.new(order_params.merge(amount_cents: rand(1000..10000), payment_method: 'credit_card'))
    if @order.save
      render json: { order: @order, payment: @order.payment }, status: :created
    else
      render json: @response.errors, status: :unprocessable_entity
    end
  end
  private
  def order_params
    params.require(:data).permit(:customer_id, :credit_card_number, :credit_card_exp_month, :credit_card_exp_year, :credit_card_cvv)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def index
      @rooms = Room.all
    end
  
    def new
      @room = Room.new
    end
  
    def create
      @room = Room.new(room_params)
      if @room.save
        flash[:success] = 'Rooms has been added Successfully!'   
  
        redirect_to  rooms_path	
      else
        render :new, status: :unprocessable_entity
      end
    end
  
     def show
        @room = Room.find(params[:id])
        flash[:notice] = 'This is Your Room List'
      end
  
      def edit
        @room = Room.find(params[:id])
       end
    
    def search
       @roomtype  = params[:roomtype]
       @results = Roomtype.where("roomtype LIKE ?", "%#{@roomtype}%")
      end

    def update
      @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = 'Product has been Updated Successfully!'   
      redirect_to rooms_path
    else
          render :edit, status: :unprocessable_entity
      end
    end
      
  private

  def room_params
    params.require(:room).permit(:roomtype_id, :roomnumber, :description, :status)
  end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
 
end
def flash_class(level)
  bootstrap_alert_class = {
    "success" => "alert-success",
    "error" => "alert-danger",
    "notice" => "alert-info",
    "alert" => "alert-danger",
    "warn" => "alert-warning"
  }
  bootstrap_alert_class[level]

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/roomtypes_helper.rb
module RoomtypesHelper
end

app/views/bookings/bookings.html.erb
<h1>Booking List</h1>




<table id="book" border="3" layout= "fixed" width=" 100%"  >
<br>
  
  <tr>
    <th>Check In</th>
    <th>Check Out</th>
    <th> Booking Date</th>
    <th>Guest Name</th>
    <th>Room Number</th>
    <th>Amount</th>
    <th>Charges</th>
    <th>Cancel Booking</th>


   
  </tr>

<% @bookings.each do |b| %>  
  <tr >
    <td><%= b.check_in%></td>
    <td><%= b.check_out %></td>
    <td><%= b.booking_date %></td>
    <td><%= b.customer.customer_name %></td>
    <td><%= b.room.roomnumber %></td>
    <td><%= b.room.roomtype.cost%></td>

    <td><%= b.charges%></td>
 <td>
<%= link_to "Cancel Booking", [b.room,b], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p><td>

  </td>

  </tr>


<% end %>
</table>

app/views/bookings/index.html.erb
<h1>Room List</h1>


<%= form_tag search_path, method: :get do %>
  <%= label_tag :roomtype, "Search for:" %>
  <%= text_field_tag :roomtype,params[:roomtype]%>
  
  <%= submit_tag "Search" %>
<% end %>


<table id="book" border="3" layout= "fixed" width=" 100%"  >
<br>
  
  <tr>
    <th>Room Number</th>
    <th>Description</th>
    <th> Status</th>
    <th> Image</th>
    
    <th>Room Type</th>
        <th>Price</th>


    <th> Action</th>
   
  </tr>

<% @rooms.each do |room| %>  

<%if room.available?%>

  <tr >
    <td><%= room.roomnumber%></td>
    <td><%= room.description %></td>
    <td><%= room.status %></td>
    <td><%=image_tag room.roomtype.roomimg, style: "width:200px; display: block"%></td>
    <td><%= room.roomtype.roomtype %></td>
        <td><%= room.roomtype.cost %></td>

     <%# <td> <%= link_to 'Booking', new_booking_path(room) ,style:"color:#ac0dfd"%>    

<td><%= link_to 'Book Now', new_room_booking_path(room), :class => 'btn btn-success btn-sm' %>

  </td>

  </tr>
  <%end%>


<% end %>
</table>

<%# <li><%= link_to "Sign Out", destroy_customer_session_path, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }</li> %> 

app/views/bookings/new.html.erb
<center>

<%= form_with model: [@room, @room.bookings.build] do |form| %>

<div class = 'card'>
  <div>
    <%= form.label :booking_date %><br>
    <%= form.date_field :booking_date %>
     <% @booking.errors.full_messages_for(:booking_date).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :check_in %><br>
    <%= form.date_field :check_in %>
     <% @booking.errors.full_messages_for(:check_in).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
  </div>

<div>
    <%= form.text_field :customer_id, value:current_customer.id,type:"hidden" %>
  </div>

  <div>
    <%= form.label :check_out %><br>
    <%= form.date_field :check_out %>
      <% @booking.errors.full_messages_for(:check_out).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.submit %>
  </div>
  </div>
  </center>

<% end %>