config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "rooms#search"
  get 'bookings/index'
  devise_for :customers
  root "bookings#index"

  
  # resources :charges, only: [:new, :create]

  get 'bookings/bookings'

   resources :roomtypes
  
   resources :rooms do  resources :bookings
    end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)



  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :booking_date, presence: true

end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_one_attached :id_proof
has_one_attached :address_proof
has_one_attached :profile_image
# has_many :bookings
# has_many :rooms
has_many :bookings
has_many :rooms, through: :bookings


def create_on_stripe
  params = { email: email, name: name }
  response = Stripe::Customer.create(params)
  self.stripe_id = response.id
end
end

app/models/order.rb
  class Order < ApplicationRecord
    attr_accessor :credit_card_number, :credit_card_exp_month, :credit_card_exp_year, :credit_card_cvv
    belongs_to :customer
    has_one :payment
    after_create :create_payment
    # Add as much as you need
    # Example: enum payment_method: %i[credit_card ach boleto]
    enum payment_method: %i[credit_card]
    def create_payment
      params = {
        order_id: id,
        credit_card_number: credit_card_number,
        credit_card_exp_month: credit_card_exp_month,
        credit_card_exp_year: credit_card_exp_year,
        credit_card_cvv: credit_card_cvv
      }
      Payment.create!(params)
    end
  end

app/models/paying.rb
class Paying < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord

  validates :roomnumber, uniqueness:true 
  belongs_to :roomtype 

  enum :status, [:available , :unavailable]
  # has_one :booking



  # belongs_to :customer

has_many :bookings ,dependent: :destroy
has_many :customers, through: :bookings

end

app/models/roomtype.rb
class Roomtype < ApplicationRecord

  has_one_attached :roomimg
  enum :status,[:booked , :opentobook]

  has_many :rooms , dependent: :destroy

  validates :roomtype, presence: true
  validates :cost, presence: true
  validates :description, presence: true



end 

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
   @rooms = Room.all
end

def bookings
    @bookings = current_customer.bookings
    @roomtype = Roomtype.all
  end


  def new
    @booking = Booking.new
    @room = Room.all
    @room = Room.find(params[:room_id])
  end

  def create
    @room = Room.find(params[:room_id])
    @booking = @room.bookings.create(booking_params)
    @room.update(status:"unavailable")

  if @booking.check_out
    @days = (@booking.check_out.to_date - @booking.check_in.to_date).to_i
    @booking.charges = @booking.room.roomtype.cost * @days
  end 
   
    if @booking.save
        BookingMailer.with(customer: current_customer, booking: @booking).welcome_email .deliver_now
      flash[:success] = 'Booking has been Done Successfully!'   
      redirect_to  root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
     @booking = Booking.find(params[:id])
     @booking.destroy

    flash[:success] = 'Booking has been Delete Successfully!'   
    redirect_to bookings_bookings_path, status: :see_other
  end

 private
  def booking_params
    params.require(:booking).permit(:customer_id, :booking_date, :check_in, :check_out)
  end
end 

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  rescue_from Stripe::CardError, with: :catch_exception
  def new
  end

  def create
    StripeChargesServices.new(charges_params, current_user).call
    redirect_to new_charge_path
  end

  private

  def charges_params
    params.permit(:stripeEmail, :stripeToken, :order_id)
  end

  def catch_exception(exception)
    flash[:error] = exception.message
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  @clients = Client.all
  end
end

app/controllers/git.rb
git add .
git commit -m "mailer"
git push origin hms

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class Api::V1::OrdersController < ApplicationController
  def create
    @order = Order.new(order_params.merge(amount_cents: rand(1000..10000), payment_method: 'credit_card'))
    if @order.save
      render json: { order: @order, payment: @order.payment }, status: :created
    else
      render json: @response.errors, status: :unprocessable_entity
    end
  end
  private
  def order_params
    params.require(:data).permit(:customer_id, :credit_card_number, :credit_card_exp_month, :credit_card_exp_year, :credit_card_cvv)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def index
      @rooms = Room.all
    end
  
    def new
      @room = Room.new
    end
  
    def create
      @room = Room.new(room_params)
      if @room.save
        flash[:success] = 'Rooms has been added Successfully!'   
  
        redirect_to  rooms_path	
      else
        render :new, status: :unprocessable_entity
      end
    end
  
     def show
        @room = Room.find(params[:id])
        flash[:notice] = 'This is Your Room List'
      end
  
      def edit
        @room = Room.find(params[:id])
       end
    
    def search
       @roomtype  = params[:roomtype]
       @results = Roomtype.where("roomtype LIKE ?", "%#{@roomtype}%")
      end

    def update
      @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = 'Product has been Updated Successfully!'   
      redirect_to rooms_path
    else
          render :edit, status: :unprocessable_entity
      end
    end
      
  private

  def room_params
    params.require(:room).permit(:roomtype_id, :roomnumber, :description, :status)
  end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
 
end
def flash_class(level)
  bootstrap_alert_class = {
    "success" => "alert-success",
    "error" => "alert-danger",
    "notice" => "alert-info",
    "alert" => "alert-danger",
    "warn" => "alert-warning"
  }
  bootstrap_alert_class[level]

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/roomtypes_helper.rb
module RoomtypesHelper
end

app/views/rooms/_form.html.erb
<center>

<%= form_with model: roomtype do |form| %>
<div class = 'card'>

   <div class="field">
    <%= form.label :roomtype_id %><br />
    <%= form.select :roomtype_id, Roomtype.all.collect{|r| [r.roomtype,r.id]} %>
  </div>


  <div>
    <%= form.label :roomnumber %><br>
    <%= form.text_area :roomnumber %>
  </div>
  <div>
    <%= form.label :description	 %><br>
    <%= form.text_area :description	 %>
  </div>

  <div>
      <%= form.label :Status	 %><br>

<%= select_tag :status, options_for_select(Room.statuses.map {|k, v| [k.humanize.capitalize, k]}) %>

  </div>

  <div>
    <%= form.submit %>
  </div>
  </div>
  </center>

<% end %>

app/views/rooms/edit.html.erb
<center>

<%= form_with model: @room do |form| %>
<div class = 'card'>

   <div class="field">
    <%= form.label :roomtype_id %><br />
    <%= form.select :roomtype_id, Roomtype.all.collect{|r| [r.roomtype,r.id]} %>
  </div>  


  <div>
    <%= form.label :roomnumber %><br>
    <%= form.text_area :roomnumber %>
  </div>
  <div>
    <%= form.label :description	 %><br>
    <%= form.text_area :description	 %>
  </div>

  <div>
      <%= form.label :Status	 %><br>

<%= form.select :status, options_for_select(Room.statuses.map {|k, v| [k.humanize.capitalize, k]}) %>

  </div>

  <div>
    <%= form.submit %>
  </div>
  </div>
  </center>

<% end %>

app/views/rooms/index.html.erb
<h1>Room List</h1>

<div class="btn btn-primary">
  <%= link_to 'Add new Room', new_room_path, :class => "btn btn-info"%> 
</div>
 <br>
<table id="book" border="3" layout= "fixed" width=" 100%"  >
<br>
  
  <tr>
    <th>roomnumber</th>
    <th>description</th>
    <th> status</th>
    <th> image</th>
    <th>room type</th>

    <th> Action</th>
   
  </tr>

<% @rooms.each do |room| %>  
  <tr >
    <td><%= room.roomnumber%></td>
    <td><%= room.description %></td>
    <td><%= room.status %></td>
    <td><%=image_tag room.roomtype.roomimg , style: "width:200px; display: block"%></td>
    <td><%= room.roomtype.roomtype %></td>
     <td> <td> <%= link_to 'Edit', edit_room_path(room) ,style:"color:#ac0dfd"%>   
</td>
  </td>

  </tr>
<% end %>
</table>

app/views/rooms/new.html.erb
<center>

<%= form_with model: @room do |form| %>
<% if @room.errors.any? %>
  <ul>
  <% @room.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  </ul>
  <%end%>
<%end%>

<div class = 'card'>

   <div class="field">
    <%= form.label :roomtype_id %><br />
    <%= form.select :roomtype_id, Roomtype.all.collect{|r| [r.roomtype,r.id]} %>
  </div>  


  <div>
    <%= form.label :roomnumber %><br>
    <%= form.text_area :roomnumber %>
  </div>
  <div>
    <%= form.label :description	 %><br>
    <%= form.text_area :description	 %>
  </div>

  <div>
      <%= form.label :Status	 %><br>

<%= form.select :status, options_for_select(Room.statuses.map {|k, v| [k.humanize.capitalize, k]}) %>

  </div>

  <div>
    <%= form.submit %>
  </div>
  </div>
  </center>

<% end %>

app/views/rooms/search.html.erb
  <table id="book" border="3" layout= "fixed" width=" 100%"  >
<br>
  
  <tr>
    <th>roomnumber</th>
    <th>description</th>
    <th> status</th>
    <th> image</th>
    <th>room type</th>

    <th> Action</th>
   
  </tr>

<% @results.each do |stock| %>  
<% stock.rooms.each do |i|%>
 <%if i.available?%>
  <tr >
    <td><%= i.roomnumber %></td>

    <td><%= i.description %></td>
    <td><%= i.status %></td>
    <td> <%=image_tag stock.roomimg , style: "width:200px; display: block"%></td>
        <td><%= i.roomtype.roomtype %></td>
                <td><%= i.roomtype.cost %></td>

        <td><%= link_to 'Book Now', new_room_booking_path(i), :class => 'btn btn-success btn-sm' %>


   </tr>
   <%end%>
   <%end%>
<% end %>
</table>
  
   
    <%= link_to 'Back To More Rooms', root_path %>

app/views/rooms/show.html.erb
  <div class="container">  
<div class = "card">      
       
            <div>   
              <label>Stock Name</label>   
              <%= @roomtype.roomtype %>   
            </div>   
  
            <div>   
              <label>Price</label>   
              <%= @roomtype.description %>   
            </div>   
            
            <div>   
              <label>Description</label>   
              <%= @roomtype.cost %>   
            </div>   
         
             
            <div>   
              <label>Country</label>   
              <%= @roomtype.status %>   
            </div>   
         
     <%=image_tag(@roomtype.roomimg)%>
        
      </div>
</div>  