config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "rooms#search"
  get 'bookings/index'
  devise_for :customers
  root "bookings#index"

  
  # resources :charges, only: [:new, :create]

  get 'bookings/bookings'

   resources :roomtypes
  
   resources :rooms do  resources :bookings
    end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)



  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :booking_date, presence: true

end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_one_attached :id_proof
has_one_attached :address_proof
has_one_attached :profile_image
# has_many :bookings
# has_many :rooms
has_many :bookings
has_many :rooms, through: :bookings


def create_on_stripe
  params = { email: email, name: name }
  response = Stripe::Customer.create(params)
  self.stripe_id = response.id
end
end

app/models/order.rb
  class Order < ApplicationRecord
    attr_accessor :credit_card_number, :credit_card_exp_month, :credit_card_exp_year, :credit_card_cvv
    belongs_to :customer
    has_one :payment
    after_create :create_payment
    # Add as much as you need
    # Example: enum payment_method: %i[credit_card ach boleto]
    enum payment_method: %i[credit_card]
    def create_payment
      params = {
        order_id: id,
        credit_card_number: credit_card_number,
        credit_card_exp_month: credit_card_exp_month,
        credit_card_exp_year: credit_card_exp_year,
        credit_card_cvv: credit_card_cvv
      }
      Payment.create!(params)
    end
  end

app/models/paying.rb
class Paying < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord

  validates :roomnumber, uniqueness:true 
  belongs_to :roomtype 

  enum :status, [:available , :unavailable]
  # has_one :booking



  # belongs_to :customer

has_many :bookings ,dependent: :destroy
has_many :customers, through: :bookings

end

app/models/roomtype.rb
class Roomtype < ApplicationRecord

  has_one_attached :roomimg
  enum :status,[:booked , :opentobook]

  has_many :rooms , dependent: :destroy

  validates :roomtype, presence: true
  validates :cost, presence: true
  validates :description, presence: true



end 

app/controllers/git.rb
git add .
git commit -m "mailer"
git push origin hms

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def index
      @rooms = Room.all
    end
  
    def new
      @room = Room.new
    end
  
    def create
      @room = Room.new(room_params)
      if @room.save
        flash[:success] = 'Rooms has been added Successfully!'   
  
        redirect_to  rooms_path	
      else
        render :new, status: :unprocessable_entity
      end
    end
  
     def show
        @room = Room.find(params[:id])
        flash[:notice] = 'This is Your Room List'
      end
  
      def edit
        @room = Room.find(params[:id])
       end
    
    def search
       @roomtype  = params[:roomtype]
       @results = Roomtype.where("roomtype LIKE ?", "%#{@roomtype}%")
      end

    def update
      @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = 'Product has been Updated Successfully!'   
      redirect_to rooms_path
    else
          render :edit, status: :unprocessable_entity
      end
    end
      
  private

  def room_params
    params.require(:room).permit(:roomtype_id, :roomnumber, :description, :status)
  end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
 
end
def flash_class(level)
  bootstrap_alert_class = {
    "success" => "alert-success",
    "error" => "alert-danger",
    "notice" => "alert-info",
    "alert" => "alert-danger",
    "warn" => "alert-warning"
  }
  bootstrap_alert_class[level]

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/roomtypes_helper.rb
module RoomtypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HMS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
 
  </head>

  <body>

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
     <div class= "container">

<%unless current_page?(new_customer_session_path)%>

     <%= render 'shared/header'%>
<%end%>
      <div class= "container">
     <% flash.each do |key, message| %>
  <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <%end%>
         <%= yield %>

  </div>
   <%= render 'shared/footer'%>

  </body>
</html>

app/views/shared/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container my-5">

    <footer style="background-color: #deded5;">
    <div class="container p-4">
      <div class="row">
        <div class="col-lg-6 col-md-12 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: #818963;">Piyush Deshmukh</h5>
          <p>
          Successful hotel management is about being able to adapt and meet challenges within a range of roles and responsibilities. Placing yourself on a scale of personal growth is especially important for a hotel manager.

There are always new strategies, traveller preferences, or industry technologies emerging to keep track of.
          </p>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: #818963;">links</h5>
          <ul class="list-unstyled mb-0">
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">Frequently Asked Questions</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">Delivery</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">Pricing</a>
            </li>
            <li>
              <a href="#!" style="color: #4f4f4f;">Where we deliver?</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-1" style="letter-spacing: 2px; color: #818963;">opening hours</h5>
          <table class="table" style="color: #4f4f4f; border-color: #666;">
            <tbody>
              <tr>
                <td>Mon - Fri:</td>
                <td>8am - 9pm</td>
              </tr>
              <tr>
                <td>Sat - Sun:</td>
                <td>8am - 1am</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">Hotel Management System</a>
    </div>
    <!-- Copyright -->
  </footer>
  
</div>
<!-- End of .container -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="bookings/bookings">View Bookings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/">Book Room </a>
        </li>

          <li class="nav-item">
          <a class="nav-link" <%=link_to "LogOut", destroy_customer_session_path, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>